### ISSUE TITLE
Status_betekenissen.md

### ISSUE THREAD

**Issue by ghost** [Piet2001/Meldkamerspel#7]
Dit bestand heeft geen lijst vorm. 
Mogelijk een idee om dit aan te passen. Zal een stuk netter staan.

**Comment by Piet2001** [comment]
Bedankt voor de melding. Staat genoteerd. Ik zal kijken wanneer ik tijd heb om het op te lossen.

**Comment by Piet2001** [comment]
Opgelost met https://github.com/Piet2001/Meldkamerspel/commit/488e7e3d1b5194bd5c525b250e9b9f0d2b21d894
